(function() {var implementors = {
"darkfi":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi/error/enum.ClientFailed.html\" title=\"enum darkfi::error::ClientFailed\">ClientFailed</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi/error/enum.Error.html\" title=\"enum darkfi::error::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi/error/enum.RpcError.html\" title=\"enum darkfi::error::RpcError\">RpcError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi/error/enum.TxVerifyFailed.html\" title=\"enum darkfi::error::TxVerifyFailed\">TxVerifyFailed</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"darkfi/system/timeout/struct.TimeoutError.html\" title=\"struct darkfi::system::timeout::TimeoutError\">TimeoutError</a>"]],
"darkfi_dao_contract":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi_dao_contract/error/enum.DaoError.html\" title=\"enum darkfi_dao_contract::error::DaoError\">DaoError</a>"]],
"darkfi_deployooor_contract":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi_deployooor_contract/error/enum.DeployError.html\" title=\"enum darkfi_deployooor_contract::error::DeployError\">DeployError</a>"]],
"darkfi_money_contract":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi_money_contract/error/enum.MoneyError.html\" title=\"enum darkfi_money_contract::error::MoneyError\">MoneyError</a>"]],
"darkfi_sdk":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi_sdk/error/enum.ContractError.html\" title=\"enum darkfi_sdk::error::ContractError\">ContractError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"darkfi_sdk/error/enum.DarkTreeError.html\" title=\"enum darkfi_sdk::error::DarkTreeError\">DarkTreeError</a>"]],
"dchatd":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"dchatd/dchat_error/struct.ErrorMissingSpecifier.html\" title=\"struct dchatd::dchat_error::ErrorMissingSpecifier\">ErrorMissingSpecifier</a>"]],
"drk":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"drk/error/enum.WalletDbError.html\" title=\"enum drk::error::WalletDbError\">WalletDbError</a>"]],
"taud":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"taud/error/enum.TaudError.html\" title=\"enum taud::error::TaudError\">TaudError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()