import os
# number of nodes
N = 10
P2PDATASTORE_PATH = '/tmp/p2pdatastore'
SLED_DB_PATH = '/tmp/sleddb'
STARTING_PORT = 53412
os.system("rm -rf " + P2PDATASTORE_PATH+"*")
os.system("rm -rf " + SLED_DB_PATH+"*")
OUTBOUND_TIMEOUT = 2
CH_HANDSHAKE_TIMEOUT = 15
CH_HEARTBEAT_INTERVAL = 15
DISCOVERY_COOLOFF = 15
DISCOVERY_ATTEMPT = 5
REFINERY_INTERVAL = 15
WHITE_CONNECT_PERCENT = 70
GOLD_CONNECT_COUNT = 2
TIME_NO_CON = 60
W8_TIME = 60
W8_TIME_4_CON = 40
