* Org directory layout
** [[inbox.org][inbox.org]]
   This is a catcher for every issue or thought that needs to be organized.
   Once a week or more often even, refile all of the items that land here.
   "Refiling" means to take a headline and all of its contents and place it
   either as sub item of another headline in the same file or different file.
   For example, assign a task to a user by refiling an item in inbox.org to
   users/<username>.org, or categorize it somewhere in the backlog someday.org.
** [[tickler.org][tickler.org]]
   Appointments or meetings, eg weekly dev meeting, conferences. All these items
   are timestamped and appear in the agenda. For example the weekly meeting will
   always appear, because it has a repeating timestamp with ~+1w~ (once a week)
** [[someday.org][someday items]]
   A backlog of items that have no assigned status, but are categorized and
   awaiting users to pick them up
** archive/*.org
   Archives of completed or abandoned tasks
** users/*.org
   User files that are refiling targets for tasks
* Various workflows
** Config settings for plugins
   Across most programs that implement orgmode, the important parts to configure
   are:
   - The agenda files, like [[tickler.org][tickler.org]] and any files in the [[users/][users directory]]
   - default org file for capturing items, in this case [[inbox.org][inbox.org]]
   - archiving items. set archiving to land in the [[archive/][archive dir]]
   You don't need to rely on the plugin to manipulate org files since they're
   just textfiles, but they provide many helpers for organizing quickly.
* Plugins
  Add any notes about setups that work or don't work if necessary
** [[https://github.com/kristijanhusak/orgmode.nvim][orgmode.nvim]] [6/7]
   Seems to work great for necessary components.
   Master branch uses tree-sitter for clocking.
   Has several add on plugins listed.
   - [X] Agenda
   - [X] Refiling
   - [X] Capturing
   - [X] Scheduling/Deadlines/Datestamps
   - [X] Clocking times
     Only with tree-sitter in vim
   - [X] Tagging
   - [ ] Tables & formulas
** [[https://github.com/dhruvasagar/vim-dotoo][vim-dotoo]] [6/7]
   - [X] Agenda
   - [X] Refiling
   - [X] Capturing
   - [X] Scheduling/Deadlines/Datestamps
   - [X] Clocking times
   - [X] Tagging
   - [ ] Tables & formulas
** [[https://github.com/jceb/vim-orgmode][vim-orgmode]]
   looks unmaintained since Jun 2021
** [[https://github.com/vscode-org-mode/vscode-org-mode][vscode-org-mode]]
   ???
